groups:
  - name: Prometheus rules
    rules:
      rules:
      - alert: PrometheusJobMissing
        expr: absent(up{job="prometheus"})
        for: 0m
        labels:
          severity: warning
        annotations:
          summary: Prometheus job missing 
          description: A Prometheus job has disappeared
      - alert: PrometheusNotConnectedToAlertmanager
        expr: prometheus_notifications_alertmanagers_discovered < 1
        for: 0m
        labels:
          severity: critical
        annotations:
          summary: Prometheus not connected to alertmanager 
          description: Prometheus cannot connect the alertmanager    
  - name: Host rules
    rules:      
      - alert: HostOutOfMemory
        expr: node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100 < 10
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: Host out of memory 
          description: Node memory is filling up (< 10% left) 
  - name: Redis rules
    rules:        
      - alert: RedisDown
        expr: redis_up == 0
        for: 0m
        labels:
          severity: critical
        annotations:
          summary: Redis down (instance {{ $labels.instance }})
          description: Redis instance is down
  - name: Nomad rules
    rules:      
     - alert: NomadJobFailed
       expr: nomad_nomad_job_summary_failed > 0
       for: 0m
       labels:
          severity: warning
       annotations:
          summary: Nomad job failed (instance {{ $labels.instance }})
          description: Nomad job failed
     - alert: NomadJobLost
       expr: nomad_nomad_job_summary_lost > 0
       for: 0m
       labels:
          severity: warning
       annotations:
          summary: Nomad job lost (instance {{ $labels.instance }})
          description: Nomad job lost