---
global:
  scrape_interval:     5s
  evaluation_interval: 5s

alerting:
  alertmanagers:
  - consul_sd_configs:
    - server: '10.0.0.10:8500'
      services: ['alertmanager']
rule_files:
  - alert.rules

scrape_configs:

  - job_name: 'nomad_metrics'
    consul_sd_configs:
      - server: '10.0.0.10:8500'
        datacenter: 'dc1'
        services: ['nomad-client', 'nomad']
    relabel_configs:                          
    - source_labels: ['__meta_consul_tags']   
      regex: '(.*)http(.*)'                   
      action: keep                            
                                              
    scrape_interval: 5s                       
    metrics_path: /v1/metrics                 
    params:                                   
      format: ['prometheus'] 

  - job_name: 'alertmanager'
    consul_sd_configs:
    - server: '10.0.0.10:8500'
      services: ['alertmanager']
    relabel_configs:
    - source_labels: [__meta_consul_service]
      target_label: job

    scrape_interval: 5s
    metrics_path: /metrics
    params:
      format: ['prometheus']   
      
      
  - job_name: 'nodes'
    consul_sd_configs:
    - server: '10.0.0.10:8500'
      services: ['node-exporter']
    relabel_configs:
    - source_labels: [__meta_consul_service]
      target_label: job
    
    scrape_interval: 5s
    metrics_path: /metrics
    params:
      format: ['prometheus']
    

  - job_name: 'redis'
    consul_sd_configs:
    - server: '10.0.0.10:8500'
      services: ['redis']     
    relabel_configs:
      - source_labels: ['__meta_consul_service']
        action: keep
        regex: (.*redis.*)  
    scrape_interval: 5s
    metrics_path: /metrics
    params:
      format: ['prometheus']     
    
  - job_name: redis-exporter
    consul_sd_configs:
    - server: '10.0.0.10:8500'
      services: ['redis-exporter']   
    relabel_configs:
    - source_labels: ['__meta_consul_service']
      target_label: job

    scrape_interval: 5s
    metrics_path: /metrics
    params:
      format: ['prometheus']   

  - job_name: 'consul-exporter'
    consul_sd_configs:
    - server: '10.0.0.10:8500'
      services: ['consul-exporter']
    relabel_configs:
    - source_labels: [__meta_consul_service]
      target_label: job

    scrape_interval: 5s
    metrics_path: /metrics
    params:
      format: ['prometheus']    
