---
global:
  scrape_interval:     5s
  evaluation_interval: 5s

alerting:
  alertmanagers:
  - consul_sd_configs:
    - server: '10.0.0.10:8500'
      services: ['alertmanager']

scrape_configs:
  - job_name: 'nomad_metrics'
    consul_sd_configs:
      - server: '10.0.0.10:8500'
        datacenter: 'dc1'
        services: ['nomad-client', 'nomad']
    relabel_configs:
      - source_labels: ['__meta_consul_tags']
        regex: '(.*)http(.*)'
        action: keep
    scrape_interval: 5s
    metrics_path: /v1/metrics
    params:
      format: ['prometheus']
      
