global:
  scrape_interval:     5s
  evaluation_interval: 5s

alerting:
  alertmanagers:
  - consul_sd_configs:
    - server: '10.0.0.10:8500'
      services: ['alertmanager']

scrape_configs:

  - job_name: 'alertmanager'

    consul_sd_configs:
    - server: '10.0.0.10:8500'
      services: ['alertmanager']

  - job_name: 'nomad_metrics'

    consul_sd_configs:
    - server: '10.0.0.10:8500'
      services: ['nomad-client', 'nomad']

    relabel_configs:
    - source_labels: ['__meta_consul_tags']
      regex: '(.*)http(.*)'
      action: keep

    scrape_interval: 5s
    metrics_path: /v1/metrics
    params:
      format: ['prometheus']

  - job_name: 'node_exporter'                 
    consul_sd_configs:                        
      - server: '10.0.0.10:8500'           
        services: ['nomad-client']        
    relabel_configs:
      - source_labels: ['__meta_consul_tags']
        regex: '(.*)http(.*)'
        action: keep
      - source_labels: [__meta_consul_service]
        target_label: job