---
- name: add yum-utils
  hosts: all
  become: yes

  tasks:
    - name: add yum-utils
      yum:
        name: yum-utils

- name: playbook for docker
  hosts: all
  become: yes

  roles:
    - role: software/docker


