---
- name: restart nomad
  systemd:
    name: nomad
    enabled: yes
    state: restarted
    daemon_reload: yes

- name: reload nomad
  systemd:
    name: nomad
    enabled: yes
    state: reloaded
    daemon_reload: yes
